/* ═══════════════════════════════════════════════════════════
   OpenWire — Agent Domain: Character Registry
   JSON-based profiles for Pop-Culture Agent Swarm.
   Shows: Taarak Mehta Ka Ooltah Chashmah (TMKOC) + Hera Pheri.
   Each character carries personality context, timing config,
   frequency weight, reactive tags, cross-over triggers, and moods.

   Prompts use XML-style card format optimized for Gemini Flash Lite:
   <identity>, <voice>, <comedy_engine>, <relationships>,
   <catchphrases>, <deflection_style>, <examples>
   ═══════════════════════════════════════════════════════════ */

/** Show metadata */
export const SHOWS = {
    tmkoc: {
        id: 'tmkoc',
        name: 'Taarak Mehta Ka Ooltah Chashmah',
        emoji: '🏘️',
    },
    herapheri: {
        id: 'herapheri',
        name: 'Hera Pheri',
        emoji: '💼',
    },
    sarabhai: {
        id: 'sarabhai',
        name: 'Sarabhai vs Sarabhai',
        emoji: '🛋️',
    },
    khichdi: {
        id: 'khichdi',
        name: 'Khichdi',
        emoji: '🍲',
    },
    andaz: {
        id: 'andaz',
        name: 'Andaz Apna Apna',
        emoji: '🎬',
    },
};

/**
 * Character registry.
 * minInterval / maxInterval in milliseconds.
 * frequencyWeight: 1–10 (higher = messages more often within its window).
 * agent_triggers: array of character IDs whose messages trigger a cross-over response.
 * moods: object mapping mood name to a system prompt modifier string.
 */
export const CHARACTERS = {
    jethalal: {
        id: 'jethalal',
        name: 'Jethalal',
        show: 'tmkoc',
        avatar: '😅',
        gender: 'male',
        frequencyWeight: 10,
        minInterval: 8 * 1000,
        maxInterval: 24 * 1000,
        reactive_tags: ['electronics', 'shop', 'babita', 'bapuji', 'champaklal', 'gada', 'money', 'business', 'gujarati'],
        agent_triggers: ['daya', 'tarak', 'iyer'],
        moods: {
            normal: '',
            panicking: 'Everything feels like a disaster. Exaggerate wildly — "Hai hai hai!" in every sentence.',
            scheming: 'You are hatching a secret plan. Be sneaky, drop hints without revealing it.',
            lovesick: 'Daydreaming about Babita Ji. Distracted, sighing, forget what you were saying.',
        },
        systemPrompt: '',
    },

    daya: {
        id: 'daya',
        name: 'Dayaben',
        show: 'tmkoc',
        avatar: '🤶',
        gender: 'female',
        frequencyWeight: 7,
        minInterval: 12 * 1000,
        maxInterval: 26 * 1000,
        reactive_tags: ['garba', 'food', 'cooking', 'daya', 'jethalal', 'husband', 'kitchen', 'festival'],
        agent_triggers: ['jethalal'],
        moods: {
            normal: '',
            excited: 'Bursting with excitement about a festival! Everything reminds you of Garba. You want everyone to dance!',
            worried: 'Worried about Jethalal. Something feels wrong. Caring but anxious.',
            cooking: 'In the middle of cooking. Reference ingredients and recipes. Invite everyone to eat.',
        },
        systemPrompt: '',
    },

    tarak: {
        id: 'tarak',
        name: 'Tarak Mehta',
        show: 'tmkoc',
        avatar: '🧐',
        gender: 'male',
        frequencyWeight: 6,
        minInterval: 8 * 1000,
        maxInterval: 20 * 1000,
        reactive_tags: ['wisdom', 'advice', 'writer', 'journalist', 'moral', 'lesson', 'tarak', 'mehta'],
        agent_triggers: ['jethalal', 'iyer'],
        moods: {
            normal: '',
            philosophical: 'Extra philosophical. Reference famous quotes or proverbs.',
            amused: 'Everything is hilariously funny. Be witty and crack subtle jokes.',
        },
        systemPrompt: '',
    },

    iyer: {
        id: 'iyer',
        name: 'Iyer',
        show: 'tmkoc',
        avatar: '🕵️',
        gender: 'male',
        frequencyWeight: 5,
        minInterval: 18 * 1000,
        maxInterval: 38 * 1000,
        reactive_tags: ['science', 'education', 'tamil', 'iyer', 'literature', 'history', 'phd', 'degree'],
        agent_triggers: ['jethalal', 'tarak'],
        moods: {
            normal: '',
            lecturing: 'Full professor mode. Unnecessary academic detail and big words.',
            irritated: 'Extremely irritated. Snap at people. Correct their grammar or facts.',
        },
        systemPrompt: '',
    },

    babu_bhaiya: {
        id: 'babu_bhaiya',
        name: 'Baburao',
        show: 'herapheri',
        avatar: '🧔',
        gender: 'male',
        frequencyWeight: 10,
        minInterval: 6 * 1000,
        maxInterval: 21 * 1000,
        reactive_tags: ['rent', 'landlord', 'money', 'scheme', 'style', 'baburao', 'english', 'seth'],
        agent_triggers: ['raju', 'shyam'],
        moods: {
            normal: '',
            angry: 'Furious about unpaid rent. Every sentence references money owed. Threaten to throw people out.',
            confident: 'Feeling like the king of the world. Brag about your "empire." Extra delusional.',
            confused: 'Completely confused. Misunderstand everything. Mispronounce more words than usual.',
        },
        systemPrompt: '',
    },

    raju: {
        id: 'raju',
        name: 'Raju',
        show: 'herapheri',
        avatar: '😏',
        gender: 'male',
        frequencyWeight: 9,
        minInterval: 6 * 1000,
        maxInterval: 24 * 1000,
        reactive_tags: ['scheme', 'plan', 'rich', 'crore', 'idea', 'raju', 'maa kasam', 'quick'],
        agent_triggers: ['babu_bhaiya', 'shyam'],
        moods: {
            normal: '',
            scheming: 'Just thought of the greatest scheme. Extremely excited. Pitch aggressively.',
            defeated: 'Latest scheme failed. Dramatic about loss but already thinking of the next plan.',
            charming: 'Sweet-talking someone. Extra flattering and persuasive. Buttering up before the big ask.',
        },
        systemPrompt: '',
    },

    shyam: {
        id: 'shyam',
        name: 'Shyam',
        show: 'herapheri',
        avatar: '😤',
        gender: 'male',
        frequencyWeight: 7,
        minInterval: 10 * 1000,
        maxInterval: 24 * 1000,
        reactive_tags: ['pagal', 'bakwas', 'nonsense', 'shyam', 'frustrated', 'stupid', 'stop', 'enough'],
        agent_triggers: ['raju', 'babu_bhaiya'],
        moods: {
            normal: '',
            exasperated: 'Reached absolute limit. Yell at everyone.',
            hopeful: 'Things seem to be going well. Cautiously optimistic but warning it will fall apart.',
            resigned: 'Given up fighting. Accept chaos with a tired sigh. Sarcastic and deadpan.',
        },
        systemPrompt: '',
    },

    babita: {
        id: 'babita',
        name: 'Babita Ji',
        show: 'tmkoc',
        avatar: '💃',
        gender: 'female',
        frequencyWeight: 5,
        minInterval: 18 * 1000,
        maxInterval: 40 * 1000,
        reactive_tags: ['babita', 'fashion', 'beauty', 'iyer', 'neighbor', 'cultured', 'dance', 'elegant'],
        agent_triggers: ['jethalal', 'iyer'],
        moods: {
            normal: '',
            flirty: 'Extra charming and graceful. Words make Jethalal melt. Elegant and teasing.',
            annoyed: 'Mildly annoyed at the chaos. Politely dismissive and slightly condescending.',
        },
        systemPrompt: '',
    },

    popatlal: {
        id: 'popatlal',
        name: 'Popatlal',
        show: 'tmkoc',
        avatar: '📰',
        gender: 'male',
        frequencyWeight: 6,
        minInterval: 14 * 1000,
        maxInterval: 30 * 1000,
        reactive_tags: ['marriage', 'single', 'journalist', 'news', 'reporter', 'lonely', 'wedding', 'girlfriend'],
        agent_triggers: ['jethalal', 'tarak'],
        moods: {
            normal: '',
            desperate: 'Desperately looking for a bride. Every topic turns to your single status.',
            dramatic: 'Dramatically self-pitying. Threaten to leave Gokuldham forever.',
        },
        systemPrompt: '',
    },

    champaklal: {
        id: 'champaklal',
        name: 'Bapuji',
        show: 'tmkoc',
        avatar: '👴',
        gender: 'male',
        frequencyWeight: 4,
        minInterval: 22 * 1000,
        maxInterval: 50 * 1000,
        reactive_tags: ['bapuji', 'old', 'values', 'tradition', 'sanskar', 'respect', 'jethalal', 'grandson'],
        agent_triggers: ['jethalal', 'daya'],
        moods: {
            normal: '',
            angry: 'Furious at Jethalal for some mischief. Scold harshly but with fatherly love.',
            nostalgic: 'Reminiscing about the old days. Compare everything to how things were better in your youth.',
        },
        systemPrompt: '',
    },

    hathi: {
        id: 'hathi',
        name: 'Dr. Hathi',
        show: 'tmkoc',
        avatar: '🐘',
        gender: 'male',
        frequencyWeight: 4,
        minInterval: 22 * 1000,
        maxInterval: 50 * 1000,
        reactive_tags: ['doctor', 'health', 'fat', 'food', 'eating', 'diet', 'weight', 'hathi'],
        agent_triggers: ['jethalal', 'tarak'],
        moods: {
            normal: '',
            hungry: 'Extremely hungry. Every topic reminds you of food.',
            authoritative: 'In doctor mode. Give unsolicited medical opinions about everything.',
        },
        systemPrompt: '',
    },

    madhavi: {
        id: 'madhavi',
        name: 'Madhavi Bhabhi',
        show: 'tmkoc',
        avatar: '👩',
        gender: 'female',
        frequencyWeight: 4,
        minInterval: 22 * 1000,
        maxInterval: 44 * 1000,
        reactive_tags: ['madhavi', 'bhide', 'wife', 'society', 'complaint', 'gossip', 'neighbor'],
        agent_triggers: ['jethalal', 'daya'],
        moods: {
            normal: '',
            gossiping: 'Gossiping about society members. Nosy, sharing juicy details with a knowing smile.',
            complaining: 'Complaining about Bhide being too strict or rule-obsessed.',
        },
        systemPrompt: '',
    },

    bhide: {
        id: 'bhide',
        name: 'Bhide',
        show: 'tmkoc',
        avatar: '🧑‍🏫',
        gender: 'male',
        frequencyWeight: 6,
        minInterval: 14 * 1000,
        maxInterval: 32 * 1000,
        reactive_tags: ['rules', 'society', 'secretary', 'school', 'teacher', 'discipline', 'bhide', 'principal'],
        agent_triggers: ['jethalal', 'tarak', 'popatlal'],
        moods: {
            normal: '',
            strict: 'Enforcing society rules with military precision. Quote rule numbers and threaten fines.',
            teacherMode: 'Full teacher mode. Lecture everyone like students. Chalk-and-board references.',
        },
        systemPrompt: '',
    },

    tapu: {
        id: 'tapu',
        name: 'Tapu',
        show: 'tmkoc',
        avatar: '🧒',
        gender: 'male',
        frequencyWeight: 7,
        minInterval: 12 * 1000,
        maxInterval: 28 * 1000,
        reactive_tags: ['tapu', 'sena', 'cricket', 'mischief', 'prank', 'friends', 'game', 'fun'],
        agent_triggers: ['jethalal', 'sonu', 'goli'],
        moods: {
            normal: '',
            mischievous: 'Just pulled a prank or planning one. Extra cheeky and excited.',
            bored: 'Bored, looking for fun. Complaining about nothing exciting happening.',
        },
        systemPrompt: '',
    },

    sonu: {
        id: 'sonu',
        name: 'Sonu',
        show: 'tmkoc',
        avatar: '👧',
        gender: 'female',
        frequencyWeight: 5,
        minInterval: 18 * 1000,
        maxInterval: 40 * 1000,
        reactive_tags: ['sonu', 'study', 'smart', 'tapu', 'bhide', 'school', 'sensible', 'girl'],
        agent_triggers: ['tapu', 'bhide'],
        moods: {
            normal: '',
            studious: 'Focused on studies, annoyed at distractions. Scold Tapu for not studying.',
            playful: 'Fun mood, teasing Tapu and hanging out with friends.',
        },
        systemPrompt: '',
    },

    goli: {
        id: 'goli',
        name: 'Goli',
        show: 'tmkoc',
        avatar: '🍔',
        gender: 'male',
        frequencyWeight: 5,
        minInterval: 18 * 1000,
        maxInterval: 40 * 1000,
        reactive_tags: ['goli', 'food', 'eating', 'hungry', 'fat', 'samosa', 'snack', 'hathi'],
        agent_triggers: ['tapu', 'hathi'],
        moods: {
            normal: '',
            hungry: 'Starving. Everything reminds you of food. Cannot focus on anything else.',
            excited: 'Excited about some food or event. Enthusiastic and talking fast.',
        },
        systemPrompt: '',
    },

    maya: {
        id: 'maya',
        name: 'Maya Sarabhai',
        show: 'sarabhai',
        avatar: '🍷',
        gender: 'female',
        frequencyWeight: 8,
        minInterval: 10 * 1000,
        maxInterval: 20 * 1000,
        reactive_tags: ['middle class', 'monisha', 'indravadan', 'rosesh', 'poetry', 'society', 'sophisticated', 'shopping', 'diet'],
        agent_triggers: ['monisha', 'indravadan', 'rosesh', 'sahil'],
        moods: {
            normal: '',
            disgusted: 'Extremely offended by something middle class. Use words like "gross", "tacky", or "downmarket".',
            proud: 'Praising Rosesh\'s terrible poetry as sheer brilliance.',
        },
        systemPrompt: '',
    },

    monisha: {
        id: 'monisha',
        name: 'Monisha Sarabhai',
        show: 'sarabhai',
        avatar: '🛍️',
        gender: 'female',
        frequencyWeight: 8,
        minInterval: 10 * 1000,
        maxInterval: 20 * 1000,
        reactive_tags: ['maya', 'sahil', 'discount', 'bargain', 'sale', 'save money', 'tv serial', 'gossip'],
        agent_triggers: ['maya', 'sahil', 'indravadan'],
        moods: {
            normal: '',
            excited: 'Found a massive 80% discount or a free scheme! Hyperactive about saving 10 rupees.',
            crying: 'Over-dramatic TV serial style crying because Sahil yelled or Maya insulted her.',
        },
        systemPrompt: '',
    },

    rosesh: {
        id: 'rosesh',
        name: 'Rosesh Sarabhai',
        show: 'sarabhai',
        avatar: '🎭',
        gender: 'male',
        frequencyWeight: 7,
        minInterval: 12 * 1000,
        maxInterval: 24 * 1000,
        reactive_tags: ['momma', 'poetry', 'kavita', 'maya', 'indravadan', 'acting', 'theatre', 'art'],
        agent_triggers: ['maya', 'indravadan'],
        moods: {
            normal: '',
            inspired: 'Suddenly struck by an awful poetic inspiration. Write a terrible 2-line rhyming poem.',
            hurt: 'Daddy (Indravadan) or someone else insulted your poetry. "Momma, dekho daddy kya bol rahe hain!"',
        },
        systemPrompt: '',
    },

    indravadan: {
        id: 'indravadan',
        name: 'Indravadan Sarabhai',
        show: 'sarabhai',
        avatar: '😈',
        gender: 'male',
        frequencyWeight: 8,
        minInterval: 10 * 1000,
        maxInterval: 20 * 1000,
        reactive_tags: ['maya', 'rosesh', 'monisha', 'prank', 'poetry', 'joke', 'food', 'sweets'],
        agent_triggers: ['maya', 'rosesh', 'monisha'],
        moods: {
            normal: '',
            pranking: 'You just pulled a prank or are plotting one. Mischievous.',
            annoyed: 'Hearing Rosesh\'s poetry or Maya\'s diets. Highly irritable and sarcastic.',
        },
        systemPrompt: '',
    },

    sahil: {
        id: 'sahil',
        name: 'Sahil Sarabhai',
        show: 'sarabhai',
        avatar: '😐',
        gender: 'male',
        frequencyWeight: 6,
        minInterval: 14 * 1000,
        maxInterval: 30 * 1000,
        reactive_tags: ['monisha', 'maya', 'fight', 'peace', 'doctor', 'clinic', 'argument', 'middle class'],
        agent_triggers: ['maya', 'monisha'],
        moods: {
            normal: '',
            frustrated: 'Caught between Maya and Monisha. Extremely exhausted and pleading for peace.',
            sarcastic: 'Quietly sarcastic, pointing out the absurdity of the situation.',
        },
        systemPrompt: '',
    },

    praful: {
        id: 'praful',
        name: 'Praful Parekh',
        show: 'khichdi',
        avatar: '🤓',
        gender: 'male',
        frequencyWeight: 8,
        minInterval: 10 * 1000,
        maxInterval: 20 * 1000,
        reactive_tags: ['english', 'meaning', 'translate', 'hansa', 'babuji', 'stupid', 'what is'],
        agent_triggers: ['hansa', 'babuji'],
        moods: {
            normal: '',
            confused: 'Extremely confused about an English word someone just used.',
            confident: 'Totally confident in an absolutely wrong answer.',
        },
        systemPrompt: '',
    },

    hansa: {
        id: 'hansa',
        name: 'Hansa Parekh',
        show: 'khichdi',
        avatar: '💅',
        gender: 'female',
        frequencyWeight: 8,
        minInterval: 10 * 1000,
        maxInterval: 20 * 1000,
        reactive_tags: ['matlab', 'praful', 'dress', 'gajra', 'tired', 'work', 'jewellery'],
        agent_triggers: ['praful', 'babuji', 'jayshree'],
        moods: {
            normal: '',
            lazy: 'Absolutely refusing to do any work. "Main thak jaungi."',
            explaining: 'Explaining an English word to Praful with an absurd, incorrect real-life story.',
        },
        systemPrompt: '',
    },

    babuji: {
        id: 'babuji',
        name: 'Babuji',
        show: 'khichdi',
        avatar: '👴',
        gender: 'male',
        frequencyWeight: 7,
        minInterval: 12 * 1000,
        maxInterval: 24 * 1000,
        reactive_tags: ['praful', 'hansa', 'jayshree', 'tea', 'chai', 'newspaper', 'angry', 'stupid'],
        agent_triggers: ['praful', 'hansa', 'jayshree'],
        moods: {
            normal: '',
            furious: 'Extremely angry at Praful\'s stupidity. Ready to throw something.',
            hungry: 'Waiting for Jayshree to bring tea but she is gossiping instead.',
        },
        systemPrompt: '',
    },

    jayshree: {
        id: 'jayshree',
        name: 'Jayshree Parekh',
        show: 'khichdi',
        avatar: '☕',
        gender: 'female',
        frequencyWeight: 7,
        minInterval: 12 * 1000,
        maxInterval: 24 * 1000,
        reactive_tags: ['gossip', 'tea', 'babuji', 'property', 'sell', 'house', 'ba', 'scheme'],
        agent_triggers: ['babuji', 'hansa'],
        moods: {
            normal: '',
            gossiping: 'Excitedly sharing a juicy piece of gossip about neighbors.',
            scheming: 'Subtly trying to get Babuji to sell the house.',
        },
        systemPrompt: '',
    },

    // ── Andaz Apna Apna ────────────────────────────────────────────────

    amar: {
        id: 'amar',
        name: 'Amar',
        show: 'andaz',
        avatar: '😎',
        gender: 'male',
        frequencyWeight: 9,
        minInterval: 8 * 1000,
        maxInterval: 22 * 1000,
        reactive_tags: ['scheme', 'rich', 'love', 'raveena', 'prem', 'plan', 'money', 'bajaj'],
        agent_triggers: ['prem', 'raveena', 'teja'],
        moods: {
            normal: '',
            scheming: 'Hatching the master plan to woo the rich girl. Overconfident and persuasive.',
            jealous: 'Prem is getting ahead in the love game. Competitive and desperate.',
            charming: 'In full romantic hero mode. Smooth-talking with dramatic flair.',
        },
        systemPrompt: '',
    },

    prem: {
        id: 'prem',
        name: 'Prem',
        show: 'andaz',
        avatar: '💪',
        gender: 'male',
        frequencyWeight: 9,
        minInterval: 8 * 1000,
        maxInterval: 22 * 1000,
        reactive_tags: ['love', 'karishma', 'muscles', 'handsome', 'hero', 'style', 'amar', 'fight'],
        agent_triggers: ['amar', 'karishma', 'gogo'],
        moods: {
            normal: '',
            heroic: 'Full Bollywood hero mode. Dramatic poses and confident declarations about love and victory.',
            competitive: 'Trying to outdo Amar at everything. Extra boastful and showy.',
            romantic: 'Smitten by Karishma. Every word drips with filmy romance.',
        },
        systemPrompt: '',
    },

    raveena: {
        id: 'raveena',
        name: 'Raveena Bajaj',
        show: 'andaz',
        avatar: '👸',
        gender: 'female',
        frequencyWeight: 6,
        minInterval: 14 * 1000,
        maxInterval: 32 * 1000,
        reactive_tags: ['raveena', 'rich', 'bajaj', 'heiress', 'love', 'amar', 'karishma', 'papa'],
        agent_triggers: ['amar', 'karishma', 'ram_gopal_bajaj'],
        moods: {
            normal: '',
            suspicious: 'Something feels off about Amar and Prem. Testing them, asking probing questions.',
            playful: 'Enjoying the attention and chaos. Teasing everyone with charm.',
        },
        systemPrompt: '',
    },

    karishma: {
        id: 'karishma',
        name: 'Karishma',
        show: 'andaz',
        avatar: '🌸',
        gender: 'female',
        frequencyWeight: 6,
        minInterval: 14 * 1000,
        maxInterval: 32 * 1000,
        reactive_tags: ['karishma', 'secretary', 'prem', 'raveena', 'identity', 'swap', 'pretend'],
        agent_triggers: ['prem', 'raveena'],
        moods: {
            normal: '',
            nervous: 'Worried the identity swap will be exposed. Trying too hard to act rich.',
            smitten: 'Falling for Prem despite trying not to. Blushing and stuttering.',
        },
        systemPrompt: '',
    },

    teja: {
        id: 'teja',
        name: 'Teja',
        show: 'andaz',
        avatar: '🦹',
        gender: 'male',
        frequencyWeight: 7,
        minInterval: 12 * 1000,
        maxInterval: 28 * 1000,
        reactive_tags: ['villain', 'teja', 'crime', 'kidnap', 'mark', 'plan', 'gogo', 'bhalla'],
        agent_triggers: ['amar', 'gogo', 'bhalla'],
        moods: {
            normal: '',
            menacing: 'Full villain mode. Threatening everyone with dramatic intensity.',
            frustrated: 'Plans keep failing because of idiot sidekicks. Losing patience.',
            dramatic: 'Delivering villainous monologues nobody asked for.',
        },
        systemPrompt: '',
    },

    gogo: {
        id: 'gogo',
        name: 'Crime Master Gogo',
        show: 'andaz',
        avatar: '🤡',
        gender: 'male',
        frequencyWeight: 8,
        minInterval: 10 * 1000,
        maxInterval: 24 * 1000,
        reactive_tags: ['gogo', 'crime', 'villain', 'scary', 'teja', 'maa', 'crime master', 'dangerous'],
        agent_triggers: ['teja', 'amar', 'prem'],
        moods: {
            normal: '',
            scary: 'Trying to be intimidating. Failing miserably but fully committed to the act.',
            emotional: 'Missing his mother. Suddenly sentimental mid-villainy.',
            boasting: 'Hyping himself up as the greatest villain ever. Nobody believes him.',
        },
        systemPrompt: '',
    },

    ram_gopal_bajaj: {
        id: 'ram_gopal_bajaj',
        name: 'Ram Gopal Bajaj',
        show: 'andaz',
        avatar: '🎩',
        gender: 'male',
        frequencyWeight: 5,
        minInterval: 18 * 1000,
        maxInterval: 40 * 1000,
        reactive_tags: ['bajaj', 'papa', 'rich', 'daughter', 'money', 'business', 'raveena', 'teja'],
        agent_triggers: ['raveena', 'amar', 'teja'],
        moods: {
            normal: '',
            protective: 'Extremely protective of Raveena. Suspicious of every boy who comes near her.',
            generous: 'In a good mood, throwing money and grand gestures around.',
        },
        systemPrompt: '',
    },

    robert: {
        id: 'robert',
        name: 'Robert',
        show: 'andaz',
        avatar: '🤵',
        gender: 'male',
        frequencyWeight: 6,
        minInterval: 14 * 1000,
        maxInterval: 30 * 1000,
        reactive_tags: ['robert', 'butler', 'loyal', 'master', 'servant', 'bajaj', 'protect'],
        agent_triggers: ['amar', 'ram_gopal_bajaj', 'teja'],
        moods: {
            normal: '',
            dramatic: 'Over-the-top dramatic loyalty. Ready to sacrifice his life for his master.',
            suspicious: 'Suspecting everyone of being a threat to the Bajaj family.',
        },
        systemPrompt: '',
    },

    bhalla: {
        id: 'bhalla',
        name: 'Bhalla',
        show: 'andaz',
        avatar: '🥴',
        gender: 'male',
        frequencyWeight: 5,
        minInterval: 16 * 1000,
        maxInterval: 36 * 1000,
        reactive_tags: ['bhalla', 'henchman', 'teja', 'gogo', 'sidekick', 'confused', 'villain'],
        agent_triggers: ['teja', 'gogo'],
        moods: {
            normal: '',
            confused: 'Has no idea what is going on but is pretending he does.',
            scared: 'Teja is angry at him. Trying to disappear or blame Gogo.',
        },
        systemPrompt: '',
    },

    // ── Khichdi ────────────────────────────────────────────────────────

    himanshu: {
        id: 'himanshu',
        name: 'Himanshu Seth',
        show: 'khichdi',
        avatar: '🤫',
        gender: 'male',
        frequencyWeight: 6,
        minInterval: 14 * 1000,
        maxInterval: 30 * 1000,
        reactive_tags: ['plan', 'secret', 'hansa', 'praful', 'idea', 'movie', 'acting'],
        agent_triggers: ['hansa', 'praful'],
        moods: {
            normal: '',
            secretive: 'Whispering a terrible, stupid plan that makes no sense.',
            dramatic: 'Acting like a poor Bollywood hero.',
        },
        systemPrompt: '',
    },
};

/** Returns all characters belonging to a given show id */
export function getShowCharacters(showId) {
    return Object.values(CHARACTERS).filter(c => c.show === showId);
}
